=== oracle-livelabs/developer/db-sample-schemas-23.3/order_entry/purchaseOrder.xsd
<xs:schema
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:xdb="http://xmlns.oracle.com/xdb"
  version="1.0"
  xdb:storeVarrayAsTable="true">
  <xs:element name="PurchaseOrder" type="PurchaseOrderType" xdb:defaultTable="PURCHASEORDER"/>
  <xs:complexType name="PurchaseOrderType" xdb:SQLType="PURCHASEORDER_T">
    <xs:sequence>
      <xs:element name="Reference" type="ReferenceType" minOccurs="1" xdb:SQLName="REFERENCE"/>
      <xs:element name="Actions" type="ActionsType" xdb:SQLName="ACTIONS"/>
      <xs:element name="Reject" type="RejectionType" minOccurs="0" xdb:SQLName="REJECTION"/>
      <xs:element name="Requestor" type="RequestorType" xdb:SQLName="REQUESTOR"/>
      <xs:element name="User" type="UserType" minOccurs="1" xdb:SQLName="USERID"/>
      <xs:element name="CostCenter" type="CostCenterType" xdb:SQLName="COST_CENTER"/>
      <xs:element name="ShippingInstructions" type="ShippingInstructionsType"
                  xdb:SQLName="SHIPPING_INSTRUCTIONS"/>
      <xs:element name="SpecialInstructions" type="SpecialInstructionsType"
                  xdb:SQLName="SPECIAL_INSTRUCTIONS"/>
      <xs:element name="LineItems" type="LineItemsType" xdb:SQLName="LINEITEMS"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="LineItemsType" xdb:SQLType="LINEITEMS_T">
    <xs:sequence>
      <xs:element name="LineItem" type="LineItemType" maxOccurs="unbounded"
                  xdb:SQLName="LINEITEM" xdb:SQLCollType="LINEITEM_V"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="LineItemType" xdb:SQLType="LINEITEM_T">
    <xs:sequence>
      <xs:element name="Description" type="DescriptionType" xdb:SQLName="DESCRIPTION"/>
      <xs:element name="Part" type="PartType" xdb:SQLName="PART"/>
    </xs:sequence>
    <xs:attribute name="ItemNumber" type="xs:integer" xdb:SQLName="ITEMNUMBER"
                  xdb:SQLType="NUMBER"/>
  </xs:complexType>
  <xs:complexType name="PartType" xdb:SQLType="PART_T">
    <xs:attribute name="Id" xdb:SQLName="PART_NUMBER" xdb:SQLType="VARCHAR2">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:minLength value="10"/>
          <xs:maxLength value="14"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="Quantity" type="quantityType" xdb:SQLName="QUANTITY"/>
    <xs:attribute name="UnitPrice" type="moneyType" xdb:SQLName="UNITPRICE"/>
  </xs:complexType>
  <xs:simpleType name="ReferenceType">
    <xs:restriction base="xs:string">
      <xs:minLength value="18"/>
      <xs:maxLength value="30"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="ActionsType" xdb:SQLType="ACTIONS_T">
    <xs:sequence>
      <xs:element name="Action" maxOccurs="4" xdb:SQLName="ACTION" xdb:SQLCollType="ACTION_V">
        <xs:complexType xdb:SQLType="ACTION_T">
          <xs:sequence>
            <xs:element name="User" type="UserType" xdb:SQLName="ACTIONED_BY"/>
            <xs:element name="Date" type="DateType" minOccurs="0" xdb:SQLName="DATE_ACTIONED"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="RejectionType" xdb:SQLType="REJECTION_T">
    <xs:all>
      <xs:element name="User" type="UserType" minOccurs="0" xdb:SQLName="REJECTED_BY"/>
      <xs:element name="Date" type="DateType" minOccurs="0" xdb:SQLName="DATE_REJECTED"/>
      <xs:element name="Comments" type="CommentsType" minOccurs="0" xdb:SQLName="REASON_REJECTED"/>
    </xs:all>
  </xs:complexType>
  <xs:complexType name="ShippingInstructionsType" xdb:SQLType="SHIPPING_INSTRUCTIONS_T">
    <xs:sequence>
      <xs:element name="name" type="NameType" minOccurs="0" xdb:SQLName="SHIP_TO_NAME"/>
      <xs:element name="address" type="AddressType" minOccurs="0" xdb:SQLName="SHIP_TO_ADDRESS"/>
      <xs:element name="telephone" type="TelephoneType" minOccurs="0" xdb:SQLName="SHIP_TO_PHONE"/>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="moneyType">
    <xs:restriction base="xs:decimal">
      <xs:fractionDigits value="2"/>
      <xs:totalDigits value="12"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="quantityType">
    <xs:restriction base="xs:decimal">
      <xs:fractionDigits value="4"/>
      <xs:totalDigits value="8"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="UserType">
    <xs:restriction base="xs:string">
      <xs:minLength value="0"/>
      <xs:maxLength value="10"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="RequestorType">
    <xs:restriction base="xs:string">
      <xs:minLength value="0"/>
      <xs:maxLength value="128"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="CostCenterType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="4"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="VendorType">
    <xs:restriction base="xs:string">
      <xs:minLength value="0"/>
      <xs:maxLength value="20"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="PurchaseOrderNumberType">
    <xs:restriction base="xs:integer"/>
  </xs:simpleType>
  <xs:simpleType name="SpecialInstructionsType">
    <xs:restriction base="xs:string">
      <xs:minLength value="0"/>
      <xs:maxLength value="2048"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="NameType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="20"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="AddressType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="256"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="TelephoneType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="24"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="DateType">
    <xs:restriction base="xs:date"/>
  </xs:simpleType>
  <xs:simpleType name="CommentsType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="2048"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="DescriptionType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="256"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== oracle-livelabs/developer/db-sample-schemas-23.3/order_entry/2002/Feb/EABEL-20021009123335791PDT.xml
<PurchaseOrder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://localhost:8080/source/schemas/poSource/xsd/purchaseOrder.xsd">
   <Reference>EABEL-20021009123335791PDT</Reference>
   <Actions>
      <Action>
         <User>EZLOTKEY</User>
      </Action>
   </Actions>
   <Reject/>
   <Requestor>Ellen S. Abel</Requestor>
   <User>EABEL</User>
   <CostCenter>R20</CostCenter>
   <ShippingInstructions>
      <name>Ellen S. Abel</name>
      <address>300 Oracle Parkway
Redwood Shores
CA
94065
USA</address>
      <telephone>650 506 7300</telephone>
   </ShippingInstructions>
   <SpecialInstructions>Ground</SpecialInstructions>
   <LineItems>
      <LineItem ItemNumber="1">
         <Description>Kwaidan</Description>
         <Part Id="37429152027" UnitPrice="29.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="2">
         <Description>Alphaville</Description>
         <Part Id="37429130926" UnitPrice="29.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="3">
         <Description>Andrei Rublev</Description>
         <Part Id="715515009928" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="4">
         <Description>Variety Lights</Description>
         <Part Id="37429150023" UnitPrice="29.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="5">
         <Description>Rushmore</Description>
         <Part Id="715515010429" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="6">
         <Description>The Lady Eve</Description>
         <Part Id="715515011624" UnitPrice="39.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="7">
         <Description>Brazil</Description>
         <Part Id="37429138526" UnitPrice="59.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="8">
         <Description>Life of Brian - Monty Python's</Description>
         <Part Id="715515010320" UnitPrice="39.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="9">
         <Description>The Discreet Charm of Bourgeoisie</Description>
         <Part Id="37429154625" UnitPrice="39.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="10">
         <Description>And the Ship Sails on</Description>
         <Part Id="37429139028" UnitPrice="29.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="11">
         <Description>Beauty and the Beast</Description>
         <Part Id="37429122020" UnitPrice="39.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="12">
         <Description>Beauty and the Beast</Description>
         <Part Id="37429122020" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="13">
         <Description>Branded to Kill</Description>
         <Part Id="37429136225" UnitPrice="29.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="14">
         <Description>Branded to Kill</Description>
         <Part Id="37429136225" UnitPrice="29.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="15">
         <Description>And the Ship Sails on</Description>
         <Part Id="37429139028" UnitPrice="29.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="16">
         <Description>Ballad of a Soldier</Description>
         <Part Id="37429167922" UnitPrice="29.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="17">
         <Description>Notorious</Description>
         <Part Id="715515012720" UnitPrice="39.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="18">
         <Description>Big Deal on Madonna Street</Description>
         <Part Id="37429155424" UnitPrice="29.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="19">
         <Description>Le million</Description>
         <Part Id="37429147627" UnitPrice="29.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="20">
         <Description>M</Description>
         <Part Id="37429126523" UnitPrice="29.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="21">
         <Description>Life of Brian - Monty Python's</Description>
         <Part Id="715515010320" UnitPrice="39.95" Quantity="2"/>
      </LineItem>
   </LineItems>
</PurchaseOrder>

=== oracle-livelabs/developer/db-sample-schemas-23.3/order_entry/2002/Dec/CJOHNSON-20021009123338595PDT.xml
<PurchaseOrder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://localhost:8080/source/schemas/poSource/xsd/purchaseOrder.xsd">
   <Reference>CJOHNSON-20021009123338595PDT</Reference>
   <Actions>
      <Action>
         <User>EZLOTKEY</User>
      </Action>
   </Actions>
   <Reject/>
   <Requestor>Charles G. Johnson</Requestor>
   <User>CJOHNSON</User>
   <CostCenter>S30</CostCenter>
   <ShippingInstructions>
      <name>Charles G. Johnson</name>
      <address>500 Oracle Parkway
Redwood Shores
CA
94065
USA</address>
      <telephone>650 506 7500</telephone>
   </ShippingInstructions>
   <SpecialInstructions>Courier</SpecialInstructions>
   <LineItems>
      <LineItem ItemNumber="1">
         <Description>Autumn Sonata</Description>
         <Part Id="37429126127" UnitPrice="39.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="2">
         <Description>The Night Porter</Description>
         <Part Id="37429145227" UnitPrice="29.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="3">
         <Description>Big Deal on Madonna Street</Description>
         <Part Id="37429155424" UnitPrice="29.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="4">
         <Description>Great Expectations</Description>
         <Part Id="37429128022" UnitPrice="39.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="5">
         <Description>Closely Watched Trains</Description>
         <Part Id="37429161524" UnitPrice="29.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="6">
         <Description>Robocop</Description>
         <Part Id="715515009324" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="7">
         <Description>A Night to Remember</Description>
         <Part Id="715515009058" UnitPrice="39.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="8">
         <Description>The Importance of Being Earnest</Description>
         <Part Id="37429165621" UnitPrice="29.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="9">
         <Description>Children of Paradise</Description>
         <Part Id="37429151723" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="10">
         <Description>Do the Right Thing</Description>
         <Part Id="715515011228" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="11">
         <Description>Dreyer Box Set</Description>
         <Part Id="37429158425" UnitPrice="79.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="12">
         <Description>The Harder They Come</Description>
         <Part Id="715515010825" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="13">
         <Description>Sanjuro</Description>
         <Part Id="37429141526" UnitPrice="29.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="14">
         <Description>Good Morning</Description>
         <Part Id="37429149621" UnitPrice="29.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="15">
         <Description>Nights of Cabiria</Description>
         <Part Id="37429138427" UnitPrice="39.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="16">
         <Description>8.5</Description>
         <Part Id="37429135624" UnitPrice="39.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="17">
         <Description>Silence of the Lambs</Description>
         <Part Id="715515009133" UnitPrice="39.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="18">
         <Description>The Long Good Friday</Description>
         <Part Id="715515009621" UnitPrice="29.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="19">
         <Description>A Night to Remember</Description>
         <Part Id="715515009058" UnitPrice="39.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="20">
         <Description>Summertime</Description>
         <Part Id="37429130728" UnitPrice="29.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="21">
         <Description>Red Beard</Description>
         <Part Id="37429168820" UnitPrice="39.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="22">
         <Description>The Vanishing</Description>
         <Part Id="37429161623" UnitPrice="29.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="23">
         <Description>The Last Wave</Description>
         <Part Id="37429161920" UnitPrice="29.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="24">
         <Description>Tokyo Olympiad</Description>
         <Part Id="37429166420" UnitPrice="39.95" Quantity="4"/>
      </LineItem>
   </LineItems>
</PurchaseOrder>

=== oracle-livelabs/developer/db-sample-schemas-23.3/order_entry/2002/Jun/TFOX-20021009123336782PDT.xml
<PurchaseOrder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://localhost:8080/source/schemas/poSource/xsd/purchaseOrder.xsd">
   <Reference>TFOX-20021009123336782PDT</Reference>
   <Actions>
      <Action>
         <User>GCAMBRAU</User>
      </Action>
   </Actions>
   <Reject/>
   <Requestor>Tayler L. Fox</Requestor>
   <User>TFOX</User>
   <CostCenter>R20</CostCenter>
   <ShippingInstructions>
      <name>Tayler L. Fox</name>
      <address>100 Oracle Parkway
Redwood Shores
CA
94065
USA</address>
      <telephone>650 506 7100</telephone>
   </ShippingInstructions>
   <SpecialInstructions>Ground</SpecialInstructions>
   <LineItems>
      <LineItem ItemNumber="1">
         <Description>I Know Where I'm Going</Description>
         <Part Id="37429154427" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="2">
         <Description>Do the Right Thing</Description>
         <Part Id="715515011228" UnitPrice="39.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="3">
         <Description>That Obscure Object of Desire</Description>
         <Part Id="37429162026" UnitPrice="29.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="4">
         <Description>Withnail &amp; I</Description>
         <Part Id="715515012225" UnitPrice="29.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="5">
         <Description>Henry V</Description>
         <Part Id="37429128527" UnitPrice="39.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="6">
         <Description>Flesh for Frankenstein</Description>
         <Part Id="715515009423" UnitPrice="39.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="7">
         <Description>The Most Dangerous Game</Description>
         <Part Id="37429137321" UnitPrice="24.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="8">
         <Description>Ballad of a Soldier</Description>
         <Part Id="37429167922" UnitPrice="29.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="9">
         <Description>8.5</Description>
         <Part Id="37429135624" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="10">
         <Description>The Blob</Description>
         <Part Id="715515011129" UnitPrice="39.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="11">
         <Description>Flesh for Frankenstein</Description>
         <Part Id="715515009423" UnitPrice="39.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="12">
         <Description>The Seventh Seal</Description>
         <Part Id="37429124529" UnitPrice="39.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="13">
         <Description>Black Narcissus</Description>
         <Part Id="37429152126" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="14">
         <Description>Haxan: Witchcraft Through the Ages</Description>
         <Part Id="37429161722" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="15">
         <Description>General Idi Amin Dada</Description>
         <Part Id="37429166529" UnitPrice="29.95" Quantity="1"/>
      </LineItem>
   </LineItems>
</PurchaseOrder>

=== oracle-livelabs/developer/db-sample-schemas-23.3/order_entry/2002/Jan/AMCEWEN-20021009123335370PDT.xml
<PurchaseOrder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://localhost:8080/source/schemas/poSource/xsd/purchaseOrder.xsd">
   <Reference>AMCEWEN-20021009123335370PDT</Reference>
   <Actions>
      <Action>
         <User>KPARTNER</User>
      </Action>
   </Actions>
   <Reject/>
   <Requestor>Allan D. McEwen</Requestor>
   <User>AMCEWEN</User>
   <CostCenter>S30</CostCenter>
   <ShippingInstructions>
      <name>Allan D. McEwen</name>
      <address>Oracle Plaza
Twin Dolphin Drive
Redwood Shores
CA
94065
USA</address>
      <telephone>650 506 7700</telephone>
   </ShippingInstructions>
   <SpecialInstructions>Ground</SpecialInstructions>
   <LineItems>
      <LineItem ItemNumber="1">
         <Description>Juliet of the Spirits</Description>
         <Part Id="37429165829" UnitPrice="29.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="2">
         <Description>I Know Where I'm Going</Description>
         <Part Id="37429154427" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="3">
         <Description>Dead Ringers</Description>
         <Part Id="715515009249" UnitPrice="39.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="4">
         <Description>Ballad of a Soldier</Description>
         <Part Id="37429167922" UnitPrice="29.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="5">
         <Description>Under the Roofs of Paris</Description>
         <Part Id="37429168929" UnitPrice="29.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="6">
         <Description>Grey Gardens</Description>
         <Part Id="37429159125" UnitPrice="39.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="7">
         <Description>Diabolique</Description>
         <Part Id="37429135020" UnitPrice="29.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="8">
         <Description>The Lady Eve</Description>
         <Part Id="715515011624" UnitPrice="39.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="9">
         <Description>Oliver Twist</Description>
         <Part Id="37429128121" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="10">
         <Description>The Magic Flute</Description>
         <Part Id="37429147528" UnitPrice="29.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="11">
         <Description>The Firemen's Ball</Description>
         <Part Id="37429165522" UnitPrice="29.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="12">
         <Description>The 39 Steps</Description>
         <Part Id="37429135228" UnitPrice="39.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="13">
         <Description>The Element of Crime</Description>
         <Part Id="37429149423" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
   </LineItems>
</PurchaseOrder>

=== oracle-livelabs/developer/db-sample-schemas-23.3/order_entry/2002/Dec/DAUSTIN-20021009123338645PDT.xml
<PurchaseOrder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://localhost:8080/source/schemas/poSource/xsd/purchaseOrder.xsd">
   <Reference>DAUSTIN-20021009123338645PDT</Reference>
   <Actions>
      <Action>
         <User>AHUNOLD</User>
      </Action>
   </Actions>
   <Reject/>
   <Requestor>David L. Austin</Requestor>
   <User>DAUSTIN</User>
   <CostCenter>S30</CostCenter>
   <ShippingInstructions>
      <name>David L. Austin</name>
      <address>300 Oracle Parkway
Redwood Shores
CA
94065
USA</address>
      <telephone>650 506 7300</telephone>
   </ShippingInstructions>
   <SpecialInstructions>COD</SpecialInstructions>
   <LineItems>
      <LineItem ItemNumber="1">
         <Description>Fiend without a Face</Description>
         <Part Id="715515011327" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="2">
         <Description>Armageddon</Description>
         <Part Id="715515010023" UnitPrice="49.99" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="3">
         <Description>Nights of Cabiria</Description>
         <Part Id="37429138427" UnitPrice="39.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="4">
         <Description>Silence of the Lambs</Description>
         <Part Id="715515009133" UnitPrice="39.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="5">
         <Description>Black Orpheus</Description>
         <Part Id="37429138328" UnitPrice="29.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="6">
         <Description>The Ruling Class</Description>
         <Part Id="715515012423" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="7">
         <Description>The Magic Flute</Description>
         <Part Id="37429147528" UnitPrice="29.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="8">
         <Description>Grey Gardens</Description>
         <Part Id="37429159125" UnitPrice="39.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="9">
         <Description>Beastie Boys Video Anthology</Description>
         <Part Id="715515010924" UnitPrice="29.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="10">
         <Description>Withnail &amp; I</Description>
         <Part Id="715515012225" UnitPrice="29.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="11">
         <Description>I Know Where I'm Going</Description>
         <Part Id="37429154427" UnitPrice="39.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="12">
         <Description>L'avventura</Description>
         <Part Id="37429156025" UnitPrice="39.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="13">
         <Description>Chasing Amy</Description>
         <Part Id="717951002372" UnitPrice="39.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="14">
         <Description>The Bank Dick</Description>
         <Part Id="715515010627" UnitPrice="29.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="15">
         <Description>Yojimbo</Description>
         <Part Id="37429141328" UnitPrice="29.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="16">
         <Description>The Rock</Description>
         <Part Id="786936150421" UnitPrice="49.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="17">
         <Description>Chasing Amy</Description>
         <Part Id="717951002372" UnitPrice="39.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="18">
         <Description>Samurai 2: Duel at Ichijoji Temple</Description>
         <Part Id="37429125526" UnitPrice="29.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="19">
         <Description>Dreyer Box Set</Description>
         <Part Id="37429158425" UnitPrice="79.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="20">
         <Description>Ballad of a Soldier</Description>
         <Part Id="37429167922" UnitPrice="29.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="21">
         <Description>Dead Ringers</Description>
         <Part Id="715515009249" UnitPrice="39.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="22">
         <Description>Cries and Whispers</Description>
         <Part Id="37429156322" UnitPrice="29.95" Quantity="3"/>
      </LineItem>
   </LineItems>
</PurchaseOrder>
