=== oracle-livelabs/developer/db-sample-schemas-23.3/order_entry/purchaseOrder.xsd
<xs:schema
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:xdb="http://xmlns.oracle.com/xdb"
  version="1.0"
  xdb:storeVarrayAsTable="true">
  <xs:element name="PurchaseOrder" type="PurchaseOrderType" xdb:defaultTable="PURCHASEORDER"/>
  <xs:complexType name="PurchaseOrderType" xdb:SQLType="PURCHASEORDER_T">
    <xs:sequence>
      <xs:element name="Reference" type="ReferenceType" minOccurs="1" xdb:SQLName="REFERENCE"/>
      <xs:element name="Actions" type="ActionsType" xdb:SQLName="ACTIONS"/>
      <xs:element name="Reject" type="RejectionType" minOccurs="0" xdb:SQLName="REJECTION"/>
      <xs:element name="Requestor" type="RequestorType" xdb:SQLName="REQUESTOR"/>
      <xs:element name="User" type="UserType" minOccurs="1" xdb:SQLName="USERID"/>
      <xs:element name="CostCenter" type="CostCenterType" xdb:SQLName="COST_CENTER"/>
      <xs:element name="ShippingInstructions" type="ShippingInstructionsType"
                  xdb:SQLName="SHIPPING_INSTRUCTIONS"/>
      <xs:element name="SpecialInstructions" type="SpecialInstructionsType"
                  xdb:SQLName="SPECIAL_INSTRUCTIONS"/>
      <xs:element name="LineItems" type="LineItemsType" xdb:SQLName="LINEITEMS"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="LineItemsType" xdb:SQLType="LINEITEMS_T">
    <xs:sequence>
      <xs:element name="LineItem" type="LineItemType" maxOccurs="unbounded"
                  xdb:SQLName="LINEITEM" xdb:SQLCollType="LINEITEM_V"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="LineItemType" xdb:SQLType="LINEITEM_T">
    <xs:sequence>
      <xs:element name="Description" type="DescriptionType" xdb:SQLName="DESCRIPTION"/>
      <xs:element name="Part" type="PartType" xdb:SQLName="PART"/>
    </xs:sequence>
    <xs:attribute name="ItemNumber" type="xs:integer" xdb:SQLName="ITEMNUMBER"
                  xdb:SQLType="NUMBER"/>
  </xs:complexType>
  <xs:complexType name="PartType" xdb:SQLType="PART_T">
    <xs:attribute name="Id" xdb:SQLName="PART_NUMBER" xdb:SQLType="VARCHAR2">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:minLength value="10"/>
          <xs:maxLength value="14"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="Quantity" type="quantityType" xdb:SQLName="QUANTITY"/>
    <xs:attribute name="UnitPrice" type="moneyType" xdb:SQLName="UNITPRICE"/>
  </xs:complexType>
  <xs:simpleType name="ReferenceType">
    <xs:restriction base="xs:string">
      <xs:minLength value="18"/>
      <xs:maxLength value="30"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="ActionsType" xdb:SQLType="ACTIONS_T">
    <xs:sequence>
      <xs:element name="Action" maxOccurs="4" xdb:SQLName="ACTION" xdb:SQLCollType="ACTION_V">
        <xs:complexType xdb:SQLType="ACTION_T">
          <xs:sequence>
            <xs:element name="User" type="UserType" xdb:SQLName="ACTIONED_BY"/>
            <xs:element name="Date" type="DateType" minOccurs="0" xdb:SQLName="DATE_ACTIONED"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="RejectionType" xdb:SQLType="REJECTION_T">
    <xs:all>
      <xs:element name="User" type="UserType" minOccurs="0" xdb:SQLName="REJECTED_BY"/>
      <xs:element name="Date" type="DateType" minOccurs="0" xdb:SQLName="DATE_REJECTED"/>
      <xs:element name="Comments" type="CommentsType" minOccurs="0" xdb:SQLName="REASON_REJECTED"/>
    </xs:all>
  </xs:complexType>
  <xs:complexType name="ShippingInstructionsType" xdb:SQLType="SHIPPING_INSTRUCTIONS_T">
    <xs:sequence>
      <xs:element name="name" type="NameType" minOccurs="0" xdb:SQLName="SHIP_TO_NAME"/>
      <xs:element name="address" type="AddressType" minOccurs="0" xdb:SQLName="SHIP_TO_ADDRESS"/>
      <xs:element name="telephone" type="TelephoneType" minOccurs="0" xdb:SQLName="SHIP_TO_PHONE"/>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="moneyType">
    <xs:restriction base="xs:decimal">
      <xs:fractionDigits value="2"/>
      <xs:totalDigits value="12"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="quantityType">
    <xs:restriction base="xs:decimal">
      <xs:fractionDigits value="4"/>
      <xs:totalDigits value="8"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="UserType">
    <xs:restriction base="xs:string">
      <xs:minLength value="0"/>
      <xs:maxLength value="10"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="RequestorType">
    <xs:restriction base="xs:string">
      <xs:minLength value="0"/>
      <xs:maxLength value="128"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="CostCenterType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="4"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="VendorType">
    <xs:restriction base="xs:string">
      <xs:minLength value="0"/>
      <xs:maxLength value="20"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="PurchaseOrderNumberType">
    <xs:restriction base="xs:integer"/>
  </xs:simpleType>
  <xs:simpleType name="SpecialInstructionsType">
    <xs:restriction base="xs:string">
      <xs:minLength value="0"/>
      <xs:maxLength value="2048"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="NameType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="20"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="AddressType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="256"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="TelephoneType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="24"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="DateType">
    <xs:restriction base="xs:date"/>
  </xs:simpleType>
  <xs:simpleType name="CommentsType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="2048"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="DescriptionType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="256"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== oracle-livelabs/developer/db-sample-schemas-23.3/order_entry/2002/Oct/TFOX-20021009123337784PDT.xml
<PurchaseOrder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://localhost:8080/source/schemas/poSource/xsd/purchaseOrder.xsd">
   <Reference>TFOX-20021009123337784PDT</Reference>
   <Actions>
      <Action>
         <User>GCAMBRAU</User>
      </Action>
   </Actions>
   <Reject/>
   <Requestor>Tayler L. Fox</Requestor>
   <User>TFOX</User>
   <CostCenter>R20</CostCenter>
   <ShippingInstructions>
      <name>Tayler L. Fox</name>
      <address>100 Oracle Parkway
Redwood Shores
CA
94065
USA</address>
      <telephone>650 506 7100</telephone>
   </ShippingInstructions>
   <SpecialInstructions>Counter to Counter</SpecialInstructions>
   <LineItems>
      <LineItem ItemNumber="1">
         <Description>And the Ship Sails on</Description>
         <Part Id="37429139028" UnitPrice="29.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="2">
         <Description>Black Narcissus</Description>
         <Part Id="37429152126" UnitPrice="39.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="3">
         <Description>Robocop</Description>
         <Part Id="715515009324" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="4">
         <Description>Sanjuro</Description>
         <Part Id="37429141526" UnitPrice="29.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="5">
         <Description>Samurai 3: Duel at Ganryu Island</Description>
         <Part Id="37429125625" UnitPrice="29.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="6">
         <Description>Time Bandits</Description>
         <Part Id="715515010122" UnitPrice="39.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="7">
         <Description>Orphic Trilogy </Description>
         <Part Id="37429148327" UnitPrice="79.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="8">
         <Description>The Bank Dick</Description>
         <Part Id="715515010627" UnitPrice="29.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="9">
         <Description>Spartacus</Description>
         <Part Id="715515011723" UnitPrice="39.96" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="10">
         <Description>Orphic Trilogy </Description>
         <Part Id="37429148327" UnitPrice="79.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="11">
         <Description>Big Deal on Madonna Street</Description>
         <Part Id="37429155424" UnitPrice="29.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="12">
         <Description>Getrud</Description>
         <Part Id="37429158524" UnitPrice="0.0" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="13">
         <Description>Orphic Trilogy </Description>
         <Part Id="37429148327" UnitPrice="79.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="14">
         <Description>Le Trou</Description>
         <Part Id="37429156223" UnitPrice="29.95" Quantity="2"/>
      </LineItem>
   </LineItems>
</PurchaseOrder>

=== oracle-livelabs/developer/db-sample-schemas-23.3/order_entry/2002/Jan/TFOX-20021009123335520PDT.xml
<PurchaseOrder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://localhost:8080/source/schemas/poSource/xsd/purchaseOrder.xsd">
   <Reference>TFOX-20021009123335520PDT</Reference>
   <Actions>
      <Action>
         <User>GCAMBRAU</User>
      </Action>
   </Actions>
   <Reject/>
   <Requestor>Tayler L. Fox</Requestor>
   <User>TFOX</User>
   <CostCenter>R20</CostCenter>
   <ShippingInstructions>
      <name>Tayler L. Fox</name>
      <address>100 Oracle Parkway
Redwood Shores
CA
94065
USA</address>
      <telephone>650 506 7100</telephone>
   </ShippingInstructions>
   <SpecialInstructions>Ground</SpecialInstructions>
   <LineItems>
      <LineItem ItemNumber="1">
         <Description>The Last Temptation of Christ</Description>
         <Part Id="715515010528" UnitPrice="39.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="2">
         <Description>Time Bandits</Description>
         <Part Id="715515010122" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="3">
         <Description>Gimme Shelter: The Rolling Stones </Description>
         <Part Id="37429154526" UnitPrice="39.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="4">
         <Description>Tokyo Olympiad</Description>
         <Part Id="37429166420" UnitPrice="39.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="5">
         <Description>Dead Ringers</Description>
         <Part Id="715515009249" UnitPrice="39.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="6">
         <Description>Rashomon  </Description>
         <Part Id="37429161821" UnitPrice="39.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="7">
         <Description>Oliver Twist</Description>
         <Part Id="37429128121" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="8">
         <Description>L'avventura</Description>
         <Part Id="37429156025" UnitPrice="39.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="9">
         <Description>Red Beard</Description>
         <Part Id="37429168820" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="10">
         <Description>Insomnia</Description>
         <Part Id="37429138229" UnitPrice="29.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="11">
         <Description>Carnival of Souls</Description>
         <Part Id="715515010221" UnitPrice="39.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="12">
         <Description>The Unbearable Lightness Of Being</Description>
         <Part Id="37429140222" UnitPrice="29.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="13">
         <Description>That Obscure Object of Desire</Description>
         <Part Id="37429162026" UnitPrice="29.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="14">
         <Description>Sid &amp; Nancy</Description>
         <Part Id="715515009232" UnitPrice="39.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="15">
         <Description>Le million</Description>
         <Part Id="37429147627" UnitPrice="29.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="16">
         <Description>Ordet</Description>
         <Part Id="37429158623" UnitPrice="0.0" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="17">
         <Description>Bob le Flambeur</Description>
         <Part Id="37429165928" UnitPrice="29.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="18">
         <Description>The Seventh Seal</Description>
         <Part Id="37429124529" UnitPrice="39.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="19">
         <Description>Cries and Whispers</Description>
         <Part Id="37429156322" UnitPrice="29.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="20">
         <Description>Peeping Tom</Description>
         <Part Id="37429142929" UnitPrice="39.95" Quantity="2"/>
      </LineItem>
   </LineItems>
</PurchaseOrder>

=== oracle-livelabs/developer/db-sample-schemas-23.3/order_entry/2002/Jun/CJOHNSON-20021009123336712PDT.xml
<PurchaseOrder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://localhost:8080/source/schemas/poSource/xsd/purchaseOrder.xsd">
   <Reference>CJOHNSON-20021009123336712PDT</Reference>
   <Actions>
      <Action>
         <User>EZLOTKEY</User>
      </Action>
   </Actions>
   <Reject/>
   <Requestor>Charles G. Johnson</Requestor>
   <User>CJOHNSON</User>
   <CostCenter>S30</CostCenter>
   <ShippingInstructions>
      <name>Charles G. Johnson</name>
      <address>500 Oracle Parkway
Redwood Shores
CA
94065
USA</address>
      <telephone>650 506 7500</telephone>
   </ShippingInstructions>
   <SpecialInstructions>Priority Overnight</SpecialInstructions>
   <LineItems>
      <LineItem ItemNumber="1">
         <Description>Red Beard</Description>
         <Part Id="37429168820" UnitPrice="39.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="2">
         <Description>Dreyer Box Set</Description>
         <Part Id="37429158425" UnitPrice="79.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="3">
         <Description>The Lady Vanishes</Description>
         <Part Id="37429122129" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="4">
         <Description>W.C. Fields - Six Short Films</Description>
         <Part Id="715515010726" UnitPrice="29.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="5">
         <Description>Beauty and the Beast</Description>
         <Part Id="37429122020" UnitPrice="39.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="6">
         <Description>Le million</Description>
         <Part Id="37429147627" UnitPrice="29.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="7">
         <Description>Juliet of the Spirits</Description>
         <Part Id="37429165829" UnitPrice="29.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="8">
         <Description>Autumn Sonata</Description>
         <Part Id="37429126127" UnitPrice="39.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="9">
         <Description>The Last Wave</Description>
         <Part Id="37429161920" UnitPrice="29.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="10">
         <Description>Chasing Amy</Description>
         <Part Id="717951002372" UnitPrice="39.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="11">
         <Description>Getrud</Description>
         <Part Id="37429158524" UnitPrice="0.0" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="12">
         <Description>The Night Porter</Description>
         <Part Id="37429145227" UnitPrice="29.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="13">
         <Description>Alphaville</Description>
         <Part Id="37429130926" UnitPrice="29.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="14">
         <Description>The Most Dangerous Game</Description>
         <Part Id="37429137321" UnitPrice="24.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="15">
         <Description>Kwaidan</Description>
         <Part Id="37429152027" UnitPrice="29.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="16">
         <Description>Coup De Torchon (Clean Slate)</Description>
         <Part Id="37429149829" UnitPrice="29.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="17">
         <Description>Variety Lights</Description>
         <Part Id="37429150023" UnitPrice="29.95" Quantity="2"/>
      </LineItem>
   </LineItems>
</PurchaseOrder>

=== oracle-livelabs/developer/db-sample-schemas-23.3/order_entry/2002/Oct/SKING-20021009123337703PDT.xml
<PurchaseOrder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://localhost:8080/source/schemas/poSource/xsd/purchaseOrder.xsd">
   <Reference>SKING-20021009123337703PDT</Reference>
   <Actions>
      <Action>
         <User/>
      </Action>
   </Actions>
   <Reject/>
   <Requestor>Steven A. King</Requestor>
   <User>SKING</User>
   <CostCenter>A10</CostCenter>
   <ShippingInstructions>
      <name>Steven A. King</name>
      <address>500 Oracle Parkway
Redwood Shores
CA
94065
USA</address>
      <telephone>650 506 7500</telephone>
   </ShippingInstructions>
   <SpecialInstructions>Hand Carry</SpecialInstructions>
   <LineItems>
      <LineItem ItemNumber="1">
         <Description>Insomnia</Description>
         <Part Id="37429138229" UnitPrice="29.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="2">
         <Description>Haxan: Witchcraft Through the Ages</Description>
         <Part Id="37429161722" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="3">
         <Description>Walkabout</Description>
         <Part Id="37429123225" UnitPrice="29.99" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="4">
         <Description>The Blob</Description>
         <Part Id="715515011129" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="5">
         <Description>Picnic at Hanging Rock</Description>
         <Part Id="37429126325" UnitPrice="29.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="6">
         <Description>Salo</Description>
         <Part Id="715515009225" UnitPrice="29.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="7">
         <Description>Getrud</Description>
         <Part Id="37429158524" UnitPrice="0.0" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="8">
         <Description>The Magic Flute</Description>
         <Part Id="37429147528" UnitPrice="29.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="9">
         <Description>How to Get Ahead in Advertising</Description>
         <Part Id="715515012324" UnitPrice="29.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="10">
         <Description>Ballad of a Soldier</Description>
         <Part Id="37429167922" UnitPrice="29.95" Quantity="3"/>
      </LineItem>
   </LineItems>
</PurchaseOrder>

=== oracle-livelabs/developer/db-sample-schemas-23.3/order_entry/2002/Aug/JCHEN-20021009123337223PDT.xml
<PurchaseOrder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://localhost:8080/source/schemas/poSource/xsd/purchaseOrder.xsd">
   <Reference>JCHEN-20021009123337223PDT</Reference>
   <Actions>
      <Action>
         <User>NGREENBE</User>
      </Action>
   </Actions>
   <Reject/>
   <Requestor>John Z. Chen</Requestor>
   <User>JCHEN</User>
   <CostCenter>A10</CostCenter>
   <ShippingInstructions>
      <name>John Z. Chen</name>
      <address>300 North First Street
Belmont
CA
94065
USA</address>
      <telephone>650 506 7200</telephone>
   </ShippingInstructions>
   <SpecialInstructions>Surface Mail</SpecialInstructions>
   <LineItems>
      <LineItem ItemNumber="1">
         <Description>Rififi</Description>
         <Part Id="37429155622" UnitPrice="29.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="2">
         <Description>Salo</Description>
         <Part Id="715515009225" UnitPrice="29.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="3">
         <Description>The Horse's Mouth</Description>
         <Part Id="37429168721" UnitPrice="29.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="4">
         <Description>Robocop</Description>
         <Part Id="715515009324" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="5">
         <Description>The Last Temptation of Christ</Description>
         <Part Id="715515010528" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="6">
         <Description>Grand Illusion</Description>
         <Part Id="37429121924" UnitPrice="39.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="7">
         <Description>The 400 Blows</Description>
         <Part Id="37429122228" UnitPrice="39.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="8">
         <Description>Sid &amp; Nancy</Description>
         <Part Id="715515009232" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="9">
         <Description>Henry V</Description>
         <Part Id="37429128527" UnitPrice="39.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="10">
         <Description>In the Mood for Love</Description>
         <Part Id="715515012928" UnitPrice="39.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="11">
         <Description>Ordet</Description>
         <Part Id="37429158623" UnitPrice="0.0" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="12">
         <Description>Salo</Description>
         <Part Id="715515009225" UnitPrice="29.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="13">
         <Description>Salesman</Description>
         <Part Id="37429158920" UnitPrice="39.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="14">
         <Description>Wild Strawberries</Description>
         <Part Id="37429162422" UnitPrice="39.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="15">
         <Description>The Night Porter</Description>
         <Part Id="37429145227" UnitPrice="29.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="16">
         <Description>Alphaville</Description>
         <Part Id="37429130926" UnitPrice="29.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="17">
         <Description>Branded to Kill</Description>
         <Part Id="37429136225" UnitPrice="29.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="18">
         <Description>Picnic at Hanging Rock</Description>
         <Part Id="37429126325" UnitPrice="29.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="19">
         <Description>Sullivan's Travels</Description>
         <Part Id="715515012126" UnitPrice="39.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="20">
         <Description>Armageddon</Description>
         <Part Id="715515010023" UnitPrice="49.99" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="21">
         <Description>Hearts and Minds</Description>
         <Part Id="37429166321" UnitPrice="39.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="22">
         <Description>Rebecca</Description>
         <Part Id="715515012522" UnitPrice="39.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="23">
         <Description>Mon Oncle</Description>
         <Part Id="37429155929" UnitPrice="29.95" Quantity="4"/>
      </LineItem>
   </LineItems>
</PurchaseOrder>

=== oracle-livelabs/developer/db-sample-schemas-23.3/order_entry/2002/Sep/TFOX-20021009123337463PDT.xml
<PurchaseOrder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://localhost:8080/source/schemas/poSource/xsd/purchaseOrder.xsd">
   <Reference>TFOX-20021009123337463PDT</Reference>
   <Actions>
      <Action>
         <User>GCAMBRAU</User>
      </Action>
   </Actions>
   <Reject/>
   <Requestor>Tayler L. Fox</Requestor>
   <User>TFOX</User>
   <CostCenter>R20</CostCenter>
   <ShippingInstructions>
      <name>Tayler L. Fox</name>
      <address>100 Oracle Parkway
Redwood Shores
CA
94065
USA</address>
      <telephone>650 506 7100</telephone>
   </ShippingInstructions>
   <SpecialInstructions>Expedite</SpecialInstructions>
   <LineItems>
      <LineItem ItemNumber="1">
         <Description>George Washington</Description>
         <Part Id="37429166123" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="2">
         <Description>Nanook of the North</Description>
         <Part Id="715515009829" UnitPrice="29.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="3">
         <Description>A Nous la Liberte</Description>
         <Part Id="37429147726" UnitPrice="29.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="4">
         <Description>Children of Paradise</Description>
         <Part Id="37429151723" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="5">
         <Description>Life of Brian - Monty Python's</Description>
         <Part Id="715515010320" UnitPrice="39.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="6">
         <Description>Billy Liar</Description>
         <Part Id="37429159224" UnitPrice="39.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="7">
         <Description>Do the Right Thing</Description>
         <Part Id="715515011228" UnitPrice="39.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="8">
         <Description>Cries and Whispers</Description>
         <Part Id="37429156322" UnitPrice="29.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="9">
         <Description>Amarcord</Description>
         <Part Id="37429121825" UnitPrice="39.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="10">
         <Description>Tokyo Drifter</Description>
         <Part Id="37429136126" UnitPrice="29.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="11">
         <Description>The Most Dangerous Game</Description>
         <Part Id="37429137321" UnitPrice="24.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="12">
         <Description>The Last Temptation of Christ</Description>
         <Part Id="715515010528" UnitPrice="39.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="13">
         <Description>Playtime</Description>
         <Part Id="37429155820" UnitPrice="29.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="14">
         <Description>L'avventura</Description>
         <Part Id="37429156025" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="15">
         <Description>Rififi</Description>
         <Part Id="37429155622" UnitPrice="29.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="16">
         <Description>High and Low</Description>
         <Part Id="37429130322" UnitPrice="39.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="17">
         <Description>Under the Roofs of Paris</Description>
         <Part Id="37429168929" UnitPrice="29.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="18">
         <Description>Time Bandits</Description>
         <Part Id="715515010122" UnitPrice="39.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="19">
         <Description>Gimme Shelter: The Rolling Stones </Description>
         <Part Id="37429154526" UnitPrice="39.95" Quantity="4"/>
      </LineItem>
   </LineItems>
</PurchaseOrder>
