=== oracle-livelabs/developer/db-sample-schemas-23.3/order_entry/purchaseOrder.xsd
<xs:schema
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:xdb="http://xmlns.oracle.com/xdb"
  version="1.0"
  xdb:storeVarrayAsTable="true">
  <xs:element name="PurchaseOrder" type="PurchaseOrderType" xdb:defaultTable="PURCHASEORDER"/>
  <xs:complexType name="PurchaseOrderType" xdb:SQLType="PURCHASEORDER_T">
    <xs:sequence>
      <xs:element name="Reference" type="ReferenceType" minOccurs="1" xdb:SQLName="REFERENCE"/>
      <xs:element name="Actions" type="ActionsType" xdb:SQLName="ACTIONS"/>
      <xs:element name="Reject" type="RejectionType" minOccurs="0" xdb:SQLName="REJECTION"/>
      <xs:element name="Requestor" type="RequestorType" xdb:SQLName="REQUESTOR"/>
      <xs:element name="User" type="UserType" minOccurs="1" xdb:SQLName="USERID"/>
      <xs:element name="CostCenter" type="CostCenterType" xdb:SQLName="COST_CENTER"/>
      <xs:element name="ShippingInstructions" type="ShippingInstructionsType"
                  xdb:SQLName="SHIPPING_INSTRUCTIONS"/>
      <xs:element name="SpecialInstructions" type="SpecialInstructionsType"
                  xdb:SQLName="SPECIAL_INSTRUCTIONS"/>
      <xs:element name="LineItems" type="LineItemsType" xdb:SQLName="LINEITEMS"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="LineItemsType" xdb:SQLType="LINEITEMS_T">
    <xs:sequence>
      <xs:element name="LineItem" type="LineItemType" maxOccurs="unbounded"
                  xdb:SQLName="LINEITEM" xdb:SQLCollType="LINEITEM_V"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="LineItemType" xdb:SQLType="LINEITEM_T">
    <xs:sequence>
      <xs:element name="Description" type="DescriptionType" xdb:SQLName="DESCRIPTION"/>
      <xs:element name="Part" type="PartType" xdb:SQLName="PART"/>
    </xs:sequence>
    <xs:attribute name="ItemNumber" type="xs:integer" xdb:SQLName="ITEMNUMBER"
                  xdb:SQLType="NUMBER"/>
  </xs:complexType>
  <xs:complexType name="PartType" xdb:SQLType="PART_T">
    <xs:attribute name="Id" xdb:SQLName="PART_NUMBER" xdb:SQLType="VARCHAR2">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:minLength value="10"/>
          <xs:maxLength value="14"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="Quantity" type="quantityType" xdb:SQLName="QUANTITY"/>
    <xs:attribute name="UnitPrice" type="moneyType" xdb:SQLName="UNITPRICE"/>
  </xs:complexType>
  <xs:simpleType name="ReferenceType">
    <xs:restriction base="xs:string">
      <xs:minLength value="18"/>
      <xs:maxLength value="30"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="ActionsType" xdb:SQLType="ACTIONS_T">
    <xs:sequence>
      <xs:element name="Action" maxOccurs="4" xdb:SQLName="ACTION" xdb:SQLCollType="ACTION_V">
        <xs:complexType xdb:SQLType="ACTION_T">
          <xs:sequence>
            <xs:element name="User" type="UserType" xdb:SQLName="ACTIONED_BY"/>
            <xs:element name="Date" type="DateType" minOccurs="0" xdb:SQLName="DATE_ACTIONED"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="RejectionType" xdb:SQLType="REJECTION_T">
    <xs:all>
      <xs:element name="User" type="UserType" minOccurs="0" xdb:SQLName="REJECTED_BY"/>
      <xs:element name="Date" type="DateType" minOccurs="0" xdb:SQLName="DATE_REJECTED"/>
      <xs:element name="Comments" type="CommentsType" minOccurs="0" xdb:SQLName="REASON_REJECTED"/>
    </xs:all>
  </xs:complexType>
  <xs:complexType name="ShippingInstructionsType" xdb:SQLType="SHIPPING_INSTRUCTIONS_T">
    <xs:sequence>
      <xs:element name="name" type="NameType" minOccurs="0" xdb:SQLName="SHIP_TO_NAME"/>
      <xs:element name="address" type="AddressType" minOccurs="0" xdb:SQLName="SHIP_TO_ADDRESS"/>
      <xs:element name="telephone" type="TelephoneType" minOccurs="0" xdb:SQLName="SHIP_TO_PHONE"/>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="moneyType">
    <xs:restriction base="xs:decimal">
      <xs:fractionDigits value="2"/>
      <xs:totalDigits value="12"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="quantityType">
    <xs:restriction base="xs:decimal">
      <xs:fractionDigits value="4"/>
      <xs:totalDigits value="8"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="UserType">
    <xs:restriction base="xs:string">
      <xs:minLength value="0"/>
      <xs:maxLength value="10"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="RequestorType">
    <xs:restriction base="xs:string">
      <xs:minLength value="0"/>
      <xs:maxLength value="128"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="CostCenterType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="4"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="VendorType">
    <xs:restriction base="xs:string">
      <xs:minLength value="0"/>
      <xs:maxLength value="20"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="PurchaseOrderNumberType">
    <xs:restriction base="xs:integer"/>
  </xs:simpleType>
  <xs:simpleType name="SpecialInstructionsType">
    <xs:restriction base="xs:string">
      <xs:minLength value="0"/>
      <xs:maxLength value="2048"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="NameType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="20"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="AddressType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="256"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="TelephoneType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="24"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="DateType">
    <xs:restriction base="xs:date"/>
  </xs:simpleType>
  <xs:simpleType name="CommentsType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="2048"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="DescriptionType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="256"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== oracle-livelabs/developer/db-sample-schemas-23.3/order_entry/2002/Jun/AWALSH-20021009123336642PDT.xml
<PurchaseOrder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://localhost:8080/source/schemas/poSource/xsd/purchaseOrder.xsd">
   <Reference>AWALSH-20021009123336642PDT</Reference>
   <Actions>
      <Action>
         <User>KPARTNER</User>
      </Action>
   </Actions>
   <Reject/>
   <Requestor>Alana G. Walsh</Requestor>
   <User>AWALSH</User>
   <CostCenter>S30</CostCenter>
   <ShippingInstructions>
      <name>Alana G. Walsh</name>
      <address>1200 East Forty Seventh Avenue 
New York
NY
10024
USA</address>
      <telephone>212 555 1212</telephone>
   </ShippingInstructions>
   <SpecialInstructions>Expedite</SpecialInstructions>
   <LineItems>
      <LineItem ItemNumber="1">
         <Description>Under the Roofs of Paris</Description>
         <Part Id="37429168929" UnitPrice="29.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="2">
         <Description>Vagabond</Description>
         <Part Id="37429148921" UnitPrice="29.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="3">
         <Description>George Washington</Description>
         <Part Id="37429166123" UnitPrice="39.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="4">
         <Description>The 400 Blows</Description>
         <Part Id="37429122228" UnitPrice="39.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="5">
         <Description>Shock Corridor</Description>
         <Part Id="37429125922" UnitPrice="29.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="6">
         <Description>The Seventh Seal</Description>
         <Part Id="37429124529" UnitPrice="39.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="7">
         <Description>Oliver Twist</Description>
         <Part Id="37429128121" UnitPrice="39.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="8">
         <Description>Salo</Description>
         <Part Id="715515009225" UnitPrice="29.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="9">
         <Description>In the Mood for Love</Description>
         <Part Id="715515012928" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="10">
         <Description>Wild Strawberries</Description>
         <Part Id="37429162422" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="11">
         <Description>Day of Wrath </Description>
         <Part Id="37429158722" UnitPrice="0.0" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="12">
         <Description>Juliet of the Spirits</Description>
         <Part Id="37429165829" UnitPrice="29.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="13">
         <Description>Time Bandits</Description>
         <Part Id="715515010122" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="14">
         <Description>Under the Roofs of Paris</Description>
         <Part Id="37429168929" UnitPrice="29.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="15">
         <Description>Variety Lights</Description>
         <Part Id="37429150023" UnitPrice="29.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="16">
         <Description>Armageddon</Description>
         <Part Id="715515010023" UnitPrice="49.99" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="17">
         <Description>Rebecca</Description>
         <Part Id="715515012522" UnitPrice="39.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="18">
         <Description>Bob le Flambeur</Description>
         <Part Id="37429165928" UnitPrice="29.95" Quantity="1"/>
      </LineItem>
   </LineItems>
</PurchaseOrder>

=== oracle-livelabs/developer/db-sample-schemas-23.3/order_entry/2002/Mar/VJONES-20021009123335971PDT.xml
<PurchaseOrder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://localhost:8080/source/schemas/poSource/xsd/purchaseOrder.xsd">
   <Reference>VJONES-20021009123335971PDT</Reference>
   <Actions>
      <Action>
         <User>SVOLLMAN</User>
      </Action>
   </Actions>
   <Reject/>
   <Requestor>Vance L. Jones</Requestor>
   <User>VJONES</User>
   <CostCenter>R20</CostCenter>
   <ShippingInstructions>
      <name>Vance L. Jones</name>
      <address>600 Oracle Parkway
Redwood Shores
CA
94065
USA</address>
      <telephone>650 506 7600</telephone>
   </ShippingInstructions>
   <SpecialInstructions>Courier</SpecialInstructions>
   <LineItems>
      <LineItem ItemNumber="1">
         <Description>George Washington</Description>
         <Part Id="37429166123" UnitPrice="39.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="2">
         <Description>Wages of Fear</Description>
         <Part Id="37429134924" UnitPrice="29.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="3">
         <Description>Grey Gardens</Description>
         <Part Id="37429159125" UnitPrice="39.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="4">
         <Description>M. Hulot's Holiday</Description>
         <Part Id="37429155721" UnitPrice="29.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="5">
         <Description>Black Orpheus</Description>
         <Part Id="37429138328" UnitPrice="29.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="6">
         <Description>Diabolique</Description>
         <Part Id="37429135020" UnitPrice="29.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="7">
         <Description>Insomnia</Description>
         <Part Id="37429138229" UnitPrice="29.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="8">
         <Description>The Firemen's Ball</Description>
         <Part Id="37429165522" UnitPrice="29.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="9">
         <Description>Dead Ringers</Description>
         <Part Id="715515009249" UnitPrice="39.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="10">
         <Description>Brazil</Description>
         <Part Id="37429138526" UnitPrice="59.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="11">
         <Description>I Know Where I'm Going</Description>
         <Part Id="37429154427" UnitPrice="39.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="12">
         <Description>Time Bandits</Description>
         <Part Id="715515010122" UnitPrice="39.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="13">
         <Description>Fiend without a Face</Description>
         <Part Id="715515011327" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="14">
         <Description>The Last Temptation of Christ</Description>
         <Part Id="715515010528" UnitPrice="39.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="15">
         <Description>The Cranes Are Flying</Description>
         <Part Id="37429168028" UnitPrice="29.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="16">
         <Description>The Bank Dick</Description>
         <Part Id="715515010627" UnitPrice="29.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="17">
         <Description>Eisenstein: The Sound Years</Description>
         <Part Id="37429149126" UnitPrice="79.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="18">
         <Description>Orpheus</Description>
         <Part Id="37429141427" UnitPrice="0.0" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="19">
         <Description>Ballad of a Soldier</Description>
         <Part Id="37429167922" UnitPrice="29.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="20">
         <Description>The Scarlet Empress</Description>
         <Part Id="715515011822" UnitPrice="29.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="21">
         <Description>Fishing With John 1 -3</Description>
         <Part Id="37429136621" UnitPrice="29.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="22">
         <Description>Dead Ringers</Description>
         <Part Id="715515009249" UnitPrice="39.95" Quantity="1"/>
      </LineItem>
   </LineItems>
</PurchaseOrder>

=== oracle-livelabs/developer/db-sample-schemas-23.3/order_entry/2002/Mar/JCHEN-20021009123335961PDT.xml
<PurchaseOrder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://localhost:8080/source/schemas/poSource/xsd/purchaseOrder.xsd">
   <Reference>JCHEN-20021009123335961PDT</Reference>
   <Actions>
      <Action>
         <User>NGREENBE</User>
      </Action>
   </Actions>
   <Reject/>
   <Requestor>John Z. Chen</Requestor>
   <User>JCHEN</User>
   <CostCenter>A10</CostCenter>
   <ShippingInstructions>
      <name>John Z. Chen</name>
      <address>300 North First Street
Belmont
CA
94065
USA</address>
      <telephone>650 506 7200</telephone>
   </ShippingInstructions>
   <SpecialInstructions>Ground</SpecialInstructions>
   <LineItems>
      <LineItem ItemNumber="1">
         <Description>A Nous la Liberte</Description>
         <Part Id="37429147726" UnitPrice="29.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="2">
         <Description>And God Created Woman</Description>
         <Part Id="37429147825" UnitPrice="29.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="3">
         <Description>Summertime</Description>
         <Part Id="37429130728" UnitPrice="29.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="4">
         <Description>Tokyo Drifter</Description>
         <Part Id="37429136126" UnitPrice="29.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="5">
         <Description>Sanjuro</Description>
         <Part Id="37429141526" UnitPrice="29.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="6">
         <Description>Peeping Tom</Description>
         <Part Id="37429142929" UnitPrice="39.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="7">
         <Description>Life of Brian - Monty Python's</Description>
         <Part Id="715515010320" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="8">
         <Description>Bob le Flambeur</Description>
         <Part Id="37429165928" UnitPrice="29.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="9">
         <Description>Ballad of a Soldier</Description>
         <Part Id="37429167922" UnitPrice="29.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="10">
         <Description>Henry V</Description>
         <Part Id="37429128527" UnitPrice="39.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="11">
         <Description>This is Spinal Tap</Description>
         <Part Id="715515009126" UnitPrice="39.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="12">
         <Description>That Obscure Object of Desire</Description>
         <Part Id="37429162026" UnitPrice="29.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="13">
         <Description>Children of Paradise</Description>
         <Part Id="37429151723" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="14">
         <Description>Diary of a Chambermaid</Description>
         <Part Id="37429158128" UnitPrice="29.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="15">
         <Description>Autumn Sonata</Description>
         <Part Id="37429126127" UnitPrice="39.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="16">
         <Description>Wages of Fear</Description>
         <Part Id="37429134924" UnitPrice="29.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="17">
         <Description>Day of Wrath </Description>
         <Part Id="37429158722" UnitPrice="0.0" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="18">
         <Description>Loves of a Blonde</Description>
         <Part Id="37429165423" UnitPrice="29.95" Quantity="1"/>
      </LineItem>
   </LineItems>
</PurchaseOrder>

=== oracle-livelabs/developer/db-sample-schemas-23.3/order_entry/2002/Mar/TFOX-2002100912333681PDT.xml
<PurchaseOrder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://localhost:8080/source/schemas/poSource/xsd/purchaseOrder.xsd">
   <Reference>TFOX-2002100912333681PDT</Reference>
   <Actions>
      <Action>
         <User>GCAMBRAU</User>
      </Action>
   </Actions>
   <Reject/>
   <Requestor>Tayler L. Fox</Requestor>
   <User>TFOX</User>
   <CostCenter>R20</CostCenter>
   <ShippingInstructions>
      <name>Tayler L. Fox</name>
      <address>100 Oracle Parkway
Redwood Shores
CA
94065
USA</address>
      <telephone>650 506 7100</telephone>
   </ShippingInstructions>
   <SpecialInstructions>Counter to Counter</SpecialInstructions>
   <LineItems>
      <LineItem ItemNumber="1">
         <Description>Autumn Sonata</Description>
         <Part Id="37429126127" UnitPrice="39.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="2">
         <Description>The Cranes Are Flying</Description>
         <Part Id="37429168028" UnitPrice="29.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="3">
         <Description>Alphaville</Description>
         <Part Id="37429130926" UnitPrice="29.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="4">
         <Description>Beauty and the Beast</Description>
         <Part Id="37429122020" UnitPrice="39.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="5">
         <Description>Seven Samurai</Description>
         <Part Id="37429121726" UnitPrice="39.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="6">
         <Description>Samurai 3: Duel at Ganryu Island</Description>
         <Part Id="37429125625" UnitPrice="29.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="7">
         <Description>Playtime</Description>
         <Part Id="37429155820" UnitPrice="29.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="8">
         <Description>The Long Good Friday</Description>
         <Part Id="715515009621" UnitPrice="29.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="9">
         <Description>The Blob</Description>
         <Part Id="715515011129" UnitPrice="39.95" Quantity="1"/>
      </LineItem>
      <LineItem ItemNumber="10">
         <Description>8.5</Description>
         <Part Id="37429135624" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="11">
         <Description>Great Expectations</Description>
         <Part Id="37429128022" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="12">
         <Description>Big Deal on Madonna Street</Description>
         <Part Id="37429155424" UnitPrice="29.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="13">
         <Description>Samurai 3: Duel at Ganryu Island</Description>
         <Part Id="37429125625" UnitPrice="29.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="14">
         <Description>Oliver Twist</Description>
         <Part Id="37429128121" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="15">
         <Description>Le Trou</Description>
         <Part Id="37429156223" UnitPrice="29.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="16">
         <Description>Beastie Boys Video Anthology</Description>
         <Part Id="715515010924" UnitPrice="29.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="17">
         <Description>All That Heaven Allows</Description>
         <Part Id="715515011426" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="18">
         <Description>Cleo from 5 to 7</Description>
         <Part Id="37429149027" UnitPrice="29.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="19">
         <Description>Diabolique</Description>
         <Part Id="37429135020" UnitPrice="29.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="20">
         <Description>Brazil</Description>
         <Part Id="37429138526" UnitPrice="59.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="21">
         <Description>Blood of a Poet</Description>
         <Part Id="37429147429" UnitPrice="0.0" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="22">
         <Description>Diabolique</Description>
         <Part Id="37429135020" UnitPrice="29.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="23">
         <Description>Dreyer Box Set</Description>
         <Part Id="37429158425" UnitPrice="79.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="24">
         <Description>Nanook of the North</Description>
         <Part Id="715515009829" UnitPrice="29.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="25">
         <Description>Orphic Trilogy </Description>
         <Part Id="37429148327" UnitPrice="79.95" Quantity="2"/>
      </LineItem>
   </LineItems>
</PurchaseOrder>

=== oracle-livelabs/developer/db-sample-schemas-23.3/order_entry/2002/May/VJONES-20021009123336502PDT.xml
<PurchaseOrder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://localhost:8080/source/schemas/poSource/xsd/purchaseOrder.xsd">
   <Reference>VJONES-20021009123336502PDT</Reference>
   <Actions>
      <Action>
         <User>SVOLLMAN</User>
      </Action>
   </Actions>
   <Reject/>
   <Requestor>Vance L. Jones</Requestor>
   <User>VJONES</User>
   <CostCenter>R20</CostCenter>
   <ShippingInstructions>
      <name>Vance L. Jones</name>
      <address>600 Oracle Parkway
Redwood Shores
CA
94065
USA</address>
      <telephone>650 506 7600</telephone>
   </ShippingInstructions>
   <SpecialInstructions>Courier</SpecialInstructions>
   <LineItems>
      <LineItem ItemNumber="1">
         <Description>Black Orpheus</Description>
         <Part Id="37429138328" UnitPrice="29.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="2">
         <Description>Charade</Description>
         <Part Id="37429139424" UnitPrice="39.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="3">
         <Description>Orpheus</Description>
         <Part Id="37429141427" UnitPrice="0.0" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="4">
         <Description>I Know Where I'm Going</Description>
         <Part Id="37429154427" UnitPrice="39.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="5">
         <Description>Wages of Fear</Description>
         <Part Id="37429134924" UnitPrice="29.95" Quantity="4"/>
      </LineItem>
      <LineItem ItemNumber="6">
         <Description>Le million</Description>
         <Part Id="37429147627" UnitPrice="29.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="7">
         <Description>The Third Man</Description>
         <Part Id="37429141625" UnitPrice="39.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="8">
         <Description>Black Orpheus</Description>
         <Part Id="37429138328" UnitPrice="29.95" Quantity="3"/>
      </LineItem>
      <LineItem ItemNumber="9">
         <Description>Salesman</Description>
         <Part Id="37429158920" UnitPrice="39.95" Quantity="2"/>
      </LineItem>
      <LineItem ItemNumber="10">
         <Description>The 400 Blows</Description>
         <Part Id="37429122228" UnitPrice="39.95" Quantity="1"/>
      </LineItem>
   </LineItems>
</PurchaseOrder>
